from django.db import models

# Create your models here.
class contactInfo(models.Model):
        first_name=models.CharField(max_length=25)
        last_name=models.CharField(max_length=25)
        email=models.CharField(max_length=40)
        phone_number=models.CharField(max_length=25)
        message=models.CharField(max_length=200)
        
def __str__(self):
        return self.first_name + ' ' + self.last_name
    
class Category(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name



class Product(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.TextField(max_length=100)
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    description_specification1 = models.TextField(max_length=800,blank=True, null=True)
    description_specification2 = models.TextField(max_length=800,blank=True, null=True)
    description_specification3 = models.TextField(max_length=800,blank=True, null=True)
    description_specification4 = models.TextField(max_length=800,blank=True, null=True)
    description_specification5 = models.TextField(max_length=800,blank=True, null=True)
    description_specification6 = models.TextField(max_length=800,blank=True, null=True)
    description_specification7 = models.TextField(max_length=800,blank=True, null=True)
    short_description = models.TextField(max_length=1200,blank=True, null=True)
    dispenser = models.TextField(max_length=1000,blank=True, null=True)
    feature_name = models.TextField(max_length=200,blank=True, null=True)
    feature = models.TextField(max_length=800,blank=True, null=True)
    feature_description = models.TextField(max_length=200,blank=True, null=True)
    short_feature = models.TextField(max_length=600,blank=True, null=True)
    height = models.CharField(max_length=200,blank=True, null=True)
    width = models.CharField(max_length=200,blank=True, null=True)
    depth = models.CharField(max_length=200,blank=True, null=True)
    length = models.CharField(max_length=200,blank=True, null=True)
    weight = models.CharField(max_length=300,blank=True, null=True)
    image_format1 = models.TextField(blank=True, null=True)
    image_format2 = models.TextField(blank=True, null=True)
    resolution = models.CharField(max_length=200,blank=True, null=True)
    scale = models.CharField(max_length=200,blank=True, null=True)
    color = models.CharField(max_length=200,blank=True, null=True)
    mode = models.CharField(max_length=200,blank=True, null=True)
    communication_specification1 = models.CharField(max_length=200,blank=True, null=True)
    communication_specification2 = models.CharField(max_length=200,blank=True, null=True)
    communication_specification3 = models.CharField(max_length=200,blank=True, null=True)
    communication_specification4 = models.CharField(max_length=200,blank=True, null=True)
    communication_specification5 = models.CharField(max_length=200,blank=True, null=True)
    gray_scale = models.CharField(max_length=200,blank=True, null=True)
    feeder = models.CharField(max_length=200,blank=True, null=True)
    reader = models.CharField(max_length=200,blank=True, null=True)
    output_guide = models.CharField(max_length=200,blank=True, null=True)
    card_scanning = models.CharField(max_length=200,blank=True, null=True)
    endoresement = models.CharField(max_length=200,blank=True, null=True)
    stamp = models.CharField(max_length=200,blank=True, null=True)
    magnetic_card = models.CharField(max_length=200,blank=True, null=True)
    chip_card = models.CharField(max_length=200,blank=True, null=True)
    security_specification1 = models.TextField(max_length=800,blank=True, null=True)
    security_specification2 = models.TextField(max_length=800,blank=True, null=True)
    security_specification3 = models.TextField(max_length=800,blank=True, null=True)
    security_specification4 = models.TextField(max_length=800,blank=True, null=True)
    module = models.CharField(max_length=400,blank=True, null=True)
    camera_specification1 = models.TextField(max_length=200,blank=True, null=True)
    camera_specification2 = models.TextField(max_length=200,blank=True, null=True)
    temparature = models.CharField(max_length=100,blank=True, null=True)
    dimension = models.CharField(max_length=200,blank=True, null=True)
    display = models.CharField(max_length=100,blank=True, null=True)
    keyboard = models.CharField(max_length=100,blank=True, null=True)
    card_reader = models.CharField(max_length=200,blank=True, null=True)
    audio = models.CharField(max_length=100,blank=True, null=True)
    barcode_reader = models.CharField(max_length=100,blank=True, null=True)
    humidity = models.CharField(max_length=100,blank=True, null=True)
    acoustic = models.CharField(max_length=100,blank=True, null=True)
    recycling_module_specification1 = models.TextField(max_length=800,blank=True, null=True)
    recycling_module_specification2 = models.TextField(max_length=800,blank=True, null=True)
    recycling_module_specification3 = models.TextField(max_length=800,blank=True, null=True)
    recycling_module_specification4 = models.TextField(max_length=800,blank=True, null=True)
    recycling_module_specification5 = models.TextField(max_length=800,blank=True, null=True)
    reciept_printer = models.CharField(max_length=200,blank=True, null=True)
    journal_printer = models.CharField(max_length=200,blank=True, null=True)
    servicing_specification1= models.CharField(max_length=200,blank=True, null=True)
    servicing_specification2= models.CharField(max_length=200,blank=True, null=True)
    operating_platform_specification1 = models.CharField(max_length=200,blank=True, null=True)
    operating_platform_specification2 = models.CharField(max_length=200,blank=True, null=True)
    operating_platform_specification3 = models.CharField(max_length=200,blank=True, null=True)
    operating_platform_specification4 = models.CharField(max_length=200,blank=True, null=True)
    software_specification1 = models.CharField(max_length=200,blank=True, null=True)
    software_specification2 = models.CharField(max_length=200,blank=True, null=True)
    printer = models.CharField(max_length=300,blank=True, null=True)
    additional_feature1 = models.CharField(max_length=100,blank=True, null=True)
    additional_feature2 = models.CharField(max_length=100,blank=True, null=True)
    additional_feature3 = models.CharField(max_length=100,blank=True, null=True)
    image1=models.ImageField(upload_to="img/%y", blank=True, null=True)
    image2=models.ImageField(upload_to="img/%y", blank=True, null=True)
    image3=models.ImageField(upload_to="img/%y", blank=True, null=True)
    brochure = models.FileField(upload_to="pdf/%y", blank=True, null=True)

    def __str__(self):
        return self.title if self.title else ''

