# Generated by Django 5.0.6 on 2024-06-12 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='contactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=40)),
                ('phone_number', models.CharField(max_length=25)),
                ('message', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=100)),
                ('description_name', models.TextField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('short_description', models.TextField(blank=True, max_length=500, null=True)),
                ('feature', models.TextField(blank=True, max_length=800, null=True)),
                ('short_feature', models.TextField(blank=True, max_length=400, null=True)),
                ('height', models.CharField(blank=True, max_length=100, null=True)),
                ('width', models.CharField(blank=True, max_length=100, null=True)),
                ('depth', models.CharField(blank=True, max_length=100, null=True)),
                ('weight', models.CharField(blank=True, max_length=100, null=True)),
                ('security', models.TextField(blank=True, max_length=800, null=True)),
                ('temparature', models.CharField(blank=True, max_length=100, null=True)),
                ('displpay', models.CharField(blank=True, max_length=100, null=True)),
                ('keyboard', models.CharField(blank=True, max_length=100, null=True)),
                ('card_reader', models.CharField(blank=True, max_length=100, null=True)),
                ('audio', models.CharField(blank=True, max_length=100, null=True)),
                ('barcode_reader', models.CharField(blank=True, max_length=100, null=True)),
                ('humidity', models.CharField(blank=True, max_length=100, null=True)),
                ('acoustic', models.CharField(blank=True, max_length=100, null=True)),
                ('recycling_module', models.CharField(blank=True, max_length=800, null=True)),
                ('reciept_printer', models.CharField(blank=True, max_length=100, null=True)),
                ('journal_printer', models.CharField(blank=True, max_length=100, null=True)),
                ('servicing', models.CharField(blank=True, max_length=200, null=True)),
                ('operating_platform', models.CharField(blank=True, max_length=200, null=True)),
                ('software', models.CharField(blank=True, max_length=200, null=True)),
                ('dispenser', models.CharField(blank=True, max_length=300, null=True)),
                ('printer', models.CharField(blank=True, max_length=300, null=True)),
                ('additional_feature', models.CharField(blank=True, max_length=100, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='img/%y')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='img/%y')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='img/%y')),
                ('brochure', models.FileField(blank=True, null=True, upload_to='pdf/%y')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='home.category')),
            ],
        ),
    ]
