# Generated by Django 5.0.6 on 2024-06-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='security',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
