# Generated by Django 5.0.6 on 2024-06-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='recycling_module_specification2',
            field=models.TextField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='recycling_module_specification3',
            field=models.TextField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='recycling_module_specification4',
            field=models.TextField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='recycling_module_specification5',
            field=models.TextField(blank=True, max_length=800, null=True),
        ),
    ]
