# Generated by Django 5.0.6 on 2024-06-06 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('description_name', models.TextField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('short_description', models.TextField(blank=True, max_length=500, null=True)),
                ('feature', models.TextField(blank=True, max_length=800, null=True)),
                ('short_feature', models.TextField(blank=True, max_length=400, null=True)),
                ('height', models.CharField(blank=True, max_length=100, null=True)),
                ('width', models.CharField(blank=True, max_length=100, null=True)),
                ('depth', models.CharField(blank=True, max_length=100, null=True)),
                ('weight', models.CharField(blank=True, max_length=100, null=True)),
                ('security', models.TextField(blank=True, max_length=200, null=True)),
                ('environmental', models.CharField(blank=True, max_length=200, null=True)),
                ('consumer_interface', models.CharField(blank=True, max_length=500, null=True)),
                ('servicing', models.CharField(blank=True, max_length=200, null=True)),
                ('operating_platform', models.CharField(blank=True, max_length=200, null=True)),
                ('software', models.CharField(blank=True, max_length=200, null=True)),
                ('dispenser', models.CharField(blank=True, max_length=300, null=True)),
                ('printer', models.CharField(blank=True, max_length=300, null=True)),
                ('Additional_Feature', models.CharField(blank=True, max_length=100, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='products/images')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='products/images')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='products/images')),
                ('Get_The_Brochure', models.FileField(blank=True, null=True, upload_to='products/pdfs/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='home.category')),
            ],
        ),
    ]
