# Generated by Django 5.0.6 on 2024-06-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_product_recycling_module_specification2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description_specification4',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_specification5',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_specification6',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_specification7',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
